### ISSUE TITLE
Website starts up in the wrong language

### ISSUE THREAD

**Issue by thaliawww-service** [thaliawww/concrexit#1016]
In GitLab by lboogaard on Mar 9, 2020, 13:03

### One-sentence description

To have a language preference in your profile so that the website starts up in your prefered language

Every time I start up the website or click on a link in the newsletter it starts up in English. I don't speak English so I would like it to start up in Dutch.

Have a cookie or something with a long time to live so that we shouldn't click on the flag every time we use the website

Cookies

Thank you in advance!
Love you!

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on Mar 9, 2020, 13:15

Are you sure your browser is not blocking cookies? Because we already have this. It's a part of Django https://docs.djangoproject.com/en/3.0/ref/settings/#language-cookie-age.

Is it possible that you changed the language of your browser to English?

**Comment by thaliawww-service** [comment]
In GitLab by lboogaard on Mar 9, 2020, 13:28

?Hello Sébastiaan,


I even have a chrome plugin that is called: 'I don't care about cookies' what enables all cookies. Furthermore, it also happens on my phone which has no plugins or sorceries whatsoever.


Kind regards,
Leon

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on Mar 9, 2020, 13:30

And in what language is your browser configured?

**Comment by thaliawww-service** [comment]
In GitLab by lboogaard on Mar 9, 2020, 15:45

?Hello Sébastiaan,


They are both set to Dutch.


Kind regards,

Leon

**Comment by se-bastiaan** [comment]
We determined that Leon had the wrong language set as primary in his browser.
