### ISSUE TITLE
Dark mode in newsletter

### ISSUE THREAD

**Issue by thaliawww-service** [thaliawww/concrexit#1019]
In GitLab by @JobDoesburg on Mar 11, 2020, 20:56

### One-sentence description

Dark mode in newsletter

### Motivation

More dark is more better

### Desired functionality

A dark mode in newsletters, just as in the regular site

### Suggested implementation

Use the same stylesheets (and svg images as well for that matter)

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on Mar 11, 2020, 23:55

I'm pretty sure not all email clients support this.

And I'm 100% sure you cannot use SVG's in emails.
https://stackoverflow.com/questions/37753911/how-can-i-embed-svg-into-html-in-an-email-so-that-its-visible-in-most-all-emai

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on Mar 11, 2020, 23:56

Oh and you cannot use SCSS to create a stylesheet that you host somewhere. The CSS has to be in the email source to support all clients.

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on Mar 11, 2020, 23:58

HTML emails are horror because of the split support between clients. Same reason why #133 has never been finished after I started work on it. I had something nice that worked in Gmail (I believe) but never finished it because it didn't work everywhere.

**Comment by thaliawww-service** [comment]
In GitLab by @JobDoesburg on Mar 12, 2020, 00:00

I know that it is possible for some mail clients, but I checked which mail clients do and don't support it and it is very limited. So I think we can close it to be honest.

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on Mar 12, 2020, 00:03

Well it's a nice idea, because my email client actually has dark mode. But it's not feasible at the moment maybe. Email sucks.

**Comment by thaliawww-service** [comment]
In GitLab by @JobDoesburg on Mar 12, 2020, 00:04

Let's use only push notifications

**Comment by se-bastiaan** [comment]
Closing because it's not feasible at the moment.
