### ISSUE TITLE
Do not use hardcoded colors for calendar API

### ISSUE THREAD

**Issue by thaliawww-service** [thaliawww/concrexit#1034]
In GitLab by @JobDoesburg on Feb 26, 2020, 21:35

### One-sentence description

Do not use hardcoded colors for calendar API in `website/members/api/serializers.py` r42-49 and `website/events/api/serializers.py`

### Why?

We shouldn't hardcode these things at the API level but provide them using CSS.

### Current implementation

The API provides a `backgroundColor` and `textColor` in the event sources APIs that is used by FullCalendar via https://fullcalendar.io/docs/events-json-feed. Every item in the feed is an event source object: https://fullcalendar.io/docs/event-source-object.

### Suggested implementation

Provide a `className` attribute instead and determine the background color and text color based on the class using CSS.

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on Feb 26, 2020, 21:37

Is this a possibility within https://fullcalendar.io/? That API is made to support FullCalendar and was thus implemented like this because they expect you to do it this way.

**Comment by thaliawww-service** [comment]
In GitLab by @JobDoesburg on Feb 26, 2020, 21:39

@pingiun told me this was a better way to do it

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on Feb 26, 2020, 21:41

I know they used FullCalendar in the GiPHouse website. So instead of reinventing the wheel and searching the documentation he may be able to tell us exactly what to change. This is quite vague for me.

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on Feb 26, 2020, 21:47

This is what we use now: https://fullcalendar.io/docs/events-json-feed

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on Feb 26, 2020, 21:48

and it looks like an event source object https://fullcalendar.io/docs/event-source-object also has the `className` attribute indeed. now I get it.

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on Feb 26, 2020, 21:51

I have clarified the description to include this. I believe it may be a good easy and fun issue that involves CSS and the APIs. Nice learning thingie.

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on Feb 26, 2020, 21:51

Oh and good idea :ok_hand:  I did not know this was possible

**Comment by thaliawww-service** [comment]
In GitLab by @marthijnvdn on Mar 4, 2020, 17:06

assigned to @marthijnvdn

**Comment by se-bastiaan** [comment]
Closed when we merged dark mode.
